### ISSUE TITLE
Week 1: Rotten Tomatoes 

### ISSUE THREAD

**Issue by ananavati** [ananavati/rotten_tomatoes#1]
Assignment submission
@timothy1ee @nesquena

**Comment by ananavati** [comment]
there is definitely room for improvement around the image resolutions and search functionality(iceberg feature lol )

**Comment by timothy1ee** [comment]
Good job!  The point of this homework was to explore a simple example of a full MVC application with a RESTful API. Nice work taking a shot at search. Note that you didn't check in UINavigationBarAlert, make sure you copy files into the workspace (it's a check box when you import).

For your information, here is the checklist that I use when I review the homework:
- Code styling. The New York Times has a good summary of appropriate Objective-C coding conventions, you should take a quick look [here](https://github.com/NYTimes/objective-c-style-guide).
- Movie model. Did you have some way to create it from a dictionary?
- You should have implemented a custom cell.  When creating a custom cell, make sure never to use imageView, titleLabel, or subtitleLabel.  Those are already used by UITableViewCell and using them in your custom cell will cause subtle things to happen such as image views not loading until you click on the cell.
- You should have loaded all the images asynchronously. One way to do that was to use AFNetworking, installed via CocoaPods.
- You should observe the UIContentMode of the UIImageView. By default, it will stretch the image to match your dimensions, which is probably not what you want.
- If you had a custom cell, you should configure the Auto Layout parameters. We'll review that in class.
- Did you display some loading indicator while you were fetching the movies.
- Did you display an error if you failed while fetching the movies.
